# Generated by Django 4.1.1 on 2022-12-03 18:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('peopleapp', '0001_initial'),
        ('tvapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='episode',
            name='director',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='tvdirector', to='peopleapp.person'),
        ),
        migrations.AddField(
            model_name='episode',
            name='writer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='tvwriter', to='peopleapp.person'),
        ),
        migrations.AlterField(
            model_name='season',
            name='status',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='season',
            name='year',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='series',
            name='status',
            field=models.IntegerField(),
        ),
    ]
