# Generated by Django 4.1.1 on 2022-12-05 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tvapp', '0003_alter_episode_season_alter_season_series'),
    ]

    operations = [
        migrations.AlterField(
            model_name='series',
            name='title',
            field=models.CharField(max_length=128, unique=True),
        ),
    ]
