# Generated by Django 4.1.1 on 2022-12-03 19:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('peopleapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('releasedate', models.DateTimeField()),
                ('mode', models.IntegerField()),
                ('artist', models.ManyToManyField(to='peopleapp.person')),
            ],
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('length', models.IntegerField()),
                ('Album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='musicapp.album')),
                ('artists', models.ManyToManyField(to='peopleapp.person')),
            ],
        ),
    ]
