# Generated by Django 4.1.1 on 2022-12-03 18:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('peopleapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('startdate', models.DateField()),
                ('enddate', models.DateField()),
                ('description', models.TextField()),
                ('status', models.IntegerField()),
                ('genres', models.TextField()),
                ('publisher', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('issueno', models.IntegerField()),
                ('releasedate', models.DateField()),
                ('description', models.TextField()),
                ('comic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comicapp.comic')),
                ('illustrator', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='illustrator', to='peopleapp.person')),
                ('writer', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='storywriter', to='peopleapp.person')),
            ],
        ),
    ]
