# Generated by Django 4.1.1 on 2022-12-02 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('releaseDate', models.DateField()),
                ('description', models.TextField()),
                ('status', models.IntegerField(max_length=1)),
                ('genres', models.TextField()),
                ('ageRating', models.TextField()),
                ('originalLanguage', models.CharField(max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
