# Generated by Django 4.1.1 on 2022-12-03 18:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('peopleapp', '0001_initial'),
        ('movieapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='director',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='filmdirector', to='peopleapp.person'),
        ),
        migrations.AddField(
            model_name='movie',
            name='writer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='filmwriter', to='peopleapp.person'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='status',
            field=models.IntegerField(),
        ),
    ]
