# Generated by Django 4.1.1 on 2022-12-05 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieapp', '0002_movie_director_movie_writer_alter_movie_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='title',
            field=models.CharField(max_length=128, unique=True),
        ),
    ]
