# Generated by Django 4.1.1 on 2022-12-05 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieapp', '0003_alter_movie_title'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='movie',
            index=models.Index(fields=['title'], name='movieapp_mo_title_b7f1ce_idx'),
        ),
    ]
