# Generated by Django 4.1.1 on 2022-12-03 18:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('peopleapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('ISBN', models.IntegerField()),
                ('description', models.TextField()),
                ('publisher', models.CharField(max_length=128)),
                ('author', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='peopleapp.person')),
            ],
        ),
    ]
